document.addEventListener('DOMContentLoaded',function(){fadeNav();window.addEventListener('scroll',fadeNav);mobileNavJs();},false);function fadeNav(){var offset=getScrollXY();if(window.innerWidth>1199){offset[1]>0?setNavOpacity("white"):setNavOpacity("transparent");}}
function setNavOpacity(newOpacity){var navBar=document.getElementById("absNav");navBar.style.backgroundColor=newOpacity;if(newOpacity=="white"){navBar.style.color="black";navBar.style.top="-10px";navBar.style.height="90px";navBar.style.boxShadow="0 0 10px rgba(0, 0, 0, .1)";document.getElementById("abstractaLogo").style.paddingTop="30px";document.getElementById("nav-logo").setAttribute("src","/resources/img/logo-abstracta.svg");document.getElementById("nav-logo").style.height="40px";var flechas=navBar.getElementsByClassName("flecha-desplegar");for(var i in flechas){flechas.item(i).setAttribute("src","/resources/img/flecha-desplegar-dark.png");}}
else{navBar.style.color="white";navBar.style.top="0px";navBar.style.height="120px";navBar.style.boxShadow="none";document.getElementById("nav-logo").setAttribute("src","/resources/img/logo-abs.svg");document.getElementById("nav-logo").style.height="50px";document.getElementById("abstractaLogo").style.paddingTop="20px";var flechas=navBar.getElementsByClassName("flecha-desplegar");for(var i in flechas){flechas.item(i).setAttribute("src","/resources/img/flecha-desplegar.png");}}}
function getScrollXY(){var scrOfX=0,scrOfY=0;if(typeof(window.pageYOffset)==='number'){scrOfY=window.pageYOffset;scrOfX=window.pageXOffset;}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){scrOfY=document.body.scrollTop;scrOfX=document.body.scrollLeft;}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){scrOfY=document.documentElement.scrollTop;scrOfX=document.documentElement.scrollLeft;}
return[scrOfX,scrOfY];}
function mobileNavJs(){var btns=document.getElementsByClassName("btn-drop-mobile");for(var b in btns){btns.item(b).onclick=function a(e){var btn=e.target;if(!btn.classList.contains('active')){var parent=btn.parentNode;for(var i=0;i<parent.childNodes.length;i++){if(parent.childNodes[i].className=="subMenu"){var subMenus=document.getElementsByClassName('subMenu');for(var e in subMenus){slideUp(subMenus.item(e));}
slideDown(parent.childNodes[i]);var botones=document.getElementsByClassName("btn-drop-mobile");for(var d in botones){botones.item(d).classList.remove('active');}
btn.classList.add('active');}}}
else{var parent=btn.parentNode;for(var i=0;i<parent.childNodes.length;i++){if(parent.childNodes[i].className=="subMenu"){var subMenus=document.getElementsByClassName('subMenu');for(var e in subMenus){slideUp(subMenus.item(e));}
btn.classList.remove('active');}}}}}
document.getElementById("btnNavBar").onclick=function c(){var mobileNav=document.getElementById("mobile-absNav");var btnNav=document.getElementById("btnNavBar");if(mobileNav.classList.contains("open")){mobileNav.style.transform="translate(0px, 0px)";mobileNav.style.webkitTransform="translateX(0px)";mobileNav.classList.remove("open");btnNav.style.transform="translate(0px, 0px)";btnNav.style.webkitTransform="translateX(0px)";}
else{mobileNav.style.transform="translate(220px, 0px)";mobileNav.style.webkitTransform="translateX(220px)";mobileNav.classList.add("open");btnNav.style.transform="translate(220px, 0px)";btnNav.style.webkitTransform="translateX(220px)";}}}
function slideDown(elem){elem.style.maxHeight='1000px';elem.style.opacity='1';}
function slideUp(elem){elem.style.maxHeight='0';elem.style.opacity='0';}
function once(seconds,callback){var counter=0;var time=window.setInterval(function(){counter++;if(counter>=seconds){callback();window.clearInterval(time);}},400);}